#!/bin/bash
#
# csc_get
#
# Used to pull exercise material from its location, which changes
# from school to school.  By localizing that here, we don't have to change
# all those instructions.
#
# This version also does minor logging via getting a logging URL
#

wget --timeout=1 --tries=1 -O /dev/null -q "http://174.105.89.157:50080/log.php?user=${USER}&file=${1}&host=${HOSTNAME}"

cp -RP csc-exercises/CSC/$1 $1
