#!/bin/bash
#
# csc_log
#
# Add an entry to the CSC exercise log with up to four parameters. 
# For example:
#  ./csc_log team Audrey Ben

wget --timeout=1 --tries=1 -O /dev/null -q "http://signer.ugis.berkeley.edu:50080/log.php?user=${USER}&item1=${1}&item2=${2}&item3=${3}&item4=${4}&host=${HOSTNAME}"
