#!/bin/bash
#
# csc_get
#
# Used to pull exercise material from its location, which changes
# from school to school.  By localizing that here, we don't have to change
# all those instructions.
# 
# This version also does minor logging via getting a logging URL
#

wget -q "http://server/jake/log.php?user=${USER}&file=${1}&host=${HOST}"

cp ~/csc-exercises/CSC/$1 ~/$1
